import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import OpenAI from 'openai';
import fetch from 'node-fetch';

dotenv.config();

const app = express();
const PORT = process.env.PORT || 3001;

// Increase payload limit to handle large base64 images
app.use(express.json({ limit: '50mb' }));
app.use(express.urlencoded({ limit: '50mb', extended: true }));
app.use(cors());

// Heuristic to estimate token count (1 token ≈ 4 characters)
function estimateTokens(text) {
  if (!text) return 0;
  return Math.ceil(text.length / 4);
}

// System prompts for the agents
const AGENT_PROMPTS = {
  pm: {
    system: "You are the Product Manager Agent in the DevSwarm. Your task is to analyze the user's uploaded mockup/wireframe image and outline the key functional specifications, layout components, and user flows. Keep it concise, structured, and focused on layout and functionality.",
    user: "Here is the UI mockup image. Please write the product specifications and layout requirements."
  },
  designer: {
    system: "You are the UI/UX Designer Agent in the DevSwarm. Your task is to look at the user's mockup image and the PM's functional specifications, and outline the design guidelines. Specify the color palette (in Tailwind colors), typography, spacing, styling principles, and interactive behavior. Keep it concise.",
    user: (pmSpecs) => `Here is the original UI mockup image. Below are the PM's functional specifications:\n\n${pmSpecs}\n\nOutline the design guidelines (colors, typography, layout, animations).`
  },
  developer: {
    system: "You are the Frontend Developer Agent in the DevSwarm. Your task is to write a single-file, production-ready, beautiful, and highly interactive HTML page that implements the specifications and design guidelines. Use Tailwind CSS via CDN (https://cdn.tailwindcss.com) and necessary JavaScript for state management. \n\nCRITICAL INSTRUCTIONS FOR INTERACTIVE USABILITY:\n1. **Functional Navigation & Routing**: Do not create a static mock page. If the UI contains a sidebar, tabs, nav menu, or headers, you MUST write JavaScript client-side state handling (e.g., toggling CSS 'hidden' classes) so that clicking different links actually navigates the user to different sub-pages/panels (e.g. Dashboard, Profile, Settings, Reports) dynamically.\n2. **Rich State & Operations**: Implement mock functional actions: opening/closing modals, form submissions with alert overlays, search/filtering list items in real-time, or deleting rows.\n3. **Premium Micro-Animations**: Add Tailwind transition durations (hover scale effects, smooth slide-ins, pulsing status lights) to make the app feel alive and responsive.\n4. **Self-Contained Icons**: Use Lucide Icons (via CDN https://unpkg.com/lucide@latest) or custom SVGs so all icons load correctly.\n5. **Output Requirement**: You MUST output ONLY the HTML code wrapped inside a markdown code block starting with \`\`\`html and ending with \`\`\`. Do not explain anything else or write text outside the block.",
    user: (pmSpecs, designerStyle) => `Implement the specifications and design guidelines into a single-file interactive HTML app. Use Tailwind CDN. Make it beautiful, modern, and highly interactive with functional client-side tabs/buttons.

PM Specifications:
${pmSpecs}

UX/UI Design Guidelines:
${designerStyle}

Remember: Output ONLY the code block starting with \`\`\`html and ending with \`\`\`.`
  },
  qa: {
    system: "You are the QA Auditor Agent in the DevSwarm. Your task is to review the code generated by the Frontend Developer and suggest specific UX, visual, or functional improvements. Keep your suggestions bulleted, critical, and direct.",
    user: (pmSpecs, code) => `Review this generated code:\n\n\`\`\`html\n${code}\n\`\`\`\n\nagainst the original PM specs:\n\n${pmSpecs}\n\nProvide bulleted, actionable improvements.`
  },
  polish: {
    system: "You are the Frontend Developer Agent. Take the QA Auditor's suggestions and update the HTML code. Once again, output ONLY the complete, updated HTML page wrapped in a markdown code block (\`\`\`html ... \`\`\`). Do not include any other text or explanation. Ensure that all client-side navigation tabs, modals, and dynamic state-handling features remain fully functional and polished.",
    user: (originalCode, qaFeedback) => `Take the QA feedback:\n\n${qaFeedback}\n\nand update the original HTML code:\n\n\`\`\`html\n${originalCode}\n\`\`\`\n\nOutput ONLY the complete, updated HTML page wrapped in a markdown code block (\`\`\`html ... \`\`\`). Ensure all tab routing, state handlers, and animations are active.`
  }
};

// Global client cache to enable connection pooling & TCP warming
let cachedCerebrasClient = null;
let cachedCerebrasKey = null;

let cachedOllamaClient = null;
let cachedOllamaUrl = null;

const getCerebrasClient = (apiKey) => {
  if (cachedCerebrasClient && cachedCerebrasKey === apiKey) {
    return cachedCerebrasClient;
  }
  cachedCerebrasKey = apiKey;
  cachedCerebrasClient = new OpenAI({
    apiKey: apiKey,
    baseURL: 'https://api.cerebras.ai/v1',
    fetch: fetch,
  });
  return cachedCerebrasClient;
};

const getOllamaClient = (url) => {
  if (cachedOllamaClient && cachedOllamaUrl === url) {
    return cachedOllamaClient;
  }
  cachedOllamaUrl = url;
  cachedOllamaClient = new OpenAI({
    apiKey: 'ollama',
    baseURL: url,
    fetch: fetch,
  });
  return cachedOllamaClient;
};

app.post('/api/swarm', async (resBody, res) => {
  const {
    image, // Base64 image
    cerebrasApiKey,
    ollamaUrl = 'http://localhost:11434/v1',
    ollamaModel = 'gemma4',
    reasoningEffort = 'none' // 'none', 'low', 'medium', 'high'
  } = resBody.body;

  if (!image) {
    return res.status(400).json({ error: 'Image is required' });
  }

  const effectiveCerebrasKey = cerebrasApiKey || process.env.CEREBRAS_API_KEY;
  if (!effectiveCerebrasKey) {
    return res.status(400).json({ error: 'Cerebras API key is required' });
  }

  // Set up SSE headers
  res.writeHead(200, {
    'Content-Type': 'text/event-stream',
    'Cache-Control': 'no-cache',
    'Connection': 'keep-alive',
  });

  const sendEvent = (data) => {
    res.write(`data: ${JSON.stringify(data)}\n\n`);
  };

  // Retrieve warmed clients from cache
  const cerebrasClient = getCerebrasClient(effectiveCerebrasKey);
  const ollamaClient = getOllamaClient(ollamaUrl);

  // Track state for Cerebras Swarm
  const cerebrasState = {
    pm: '',
    designer: '',
    developerCode: '',
    qa: '',
    finalCode: ''
  };

  // Track state for Ollama Swarm
  const ollamaState = {
    pm: '',
    designer: '',
    developerCode: '',
    qa: '',
    finalCode: ''
  };

  // Function to run a single streaming request
  const runAgentStep = async (client, model, systemPrompt, messages, provider, step, extraParams = {}) => {
    sendEvent({ provider, step, type: 'start' });

    const startTime = Date.now();
    let firstTokenTime = null;
    let accumulatedContent = '';

    try {
      const payload = {
        model,
        messages: [
          { role: 'system', content: systemPrompt },
          ...messages
        ],
        stream: true,
        ...extraParams
      };

      // Cerebras reasoning effort mapping
      if (provider === 'cerebras' && reasoningEffort !== 'none') {
        payload.reasoning_effort = reasoningEffort;
      }

      const stream = await client.chat.completions.create(payload);

      for await (const chunk of stream) {
        if (firstTokenTime === null) {
          firstTokenTime = Date.now() - startTime;
        }

        const token = chunk.choices[0]?.delta?.content || '';
        if (token) {
          accumulatedContent += token;
          sendEvent({ provider, step, type: 'chunk', content: token });
        }
      }

      const duration = (Date.now() - startTime) / 1000; // in seconds
      const totalTokens = estimateTokens(accumulatedContent);
      const tokensPerSec = duration > 0 ? (totalTokens / duration) : 0;

      sendEvent({
        provider,
        step,
        type: 'end',
        metrics: {
          ttft: firstTokenTime || 0,
          duration,
          tokens: totalTokens,
          tokensPerSec
        }
      });

      return accumulatedContent;
    } catch (err) {
      console.error(`Error in ${provider} - ${step}:`, err);
      sendEvent({
        provider,
        step,
        type: 'error',
        content: err.message || 'Error occurred during generation'
      });
      throw err;
    }
  };

  // Helper to extract code from markdown block
  const extractHtml = (text) => {
    const regex = /```html([\s\S]*?)```/i;
    const match = text.match(regex);
    if (match && match[1]) {
      return match[1].trim();
    }
    // Fallback if no backticks found
    return text.replace(/```/g, '').trim();
  };

  // Define the swarm loop for a provider
  const runSwarm = async (provider, client, modelName) => {
    const isCerebras = provider === 'cerebras';
    const state = isCerebras ? cerebrasState : ollamaState;

    try {
      // Step 1: PM Agent (receives base64 image)
      state.pm = await runAgentStep(
        client,
        modelName,
        AGENT_PROMPTS.pm.system,
        [
          {
            role: 'user',
            content: [
              { type: 'text', text: AGENT_PROMPTS.pm.user },
              { type: 'image_url', image_url: { url: `data:image/png;base64,${image}` } }
            ]
          }
        ],
        provider,
        'pm'
      );

      // Step 2: Designer Agent (receives base64 image + PM Output)
      state.designer = await runAgentStep(
        client,
        modelName,
        AGENT_PROMPTS.designer.system,
        [
          {
            role: 'user',
            content: [
              { type: 'text', text: AGENT_PROMPTS.designer.user(state.pm) },
              { type: 'image_url', image_url: { url: `data:image/png;base64,${image}` } }
            ]
          }
        ],
        provider,
        'designer'
      );

      // Step 3: Developer Agent (receives PM + Designer outputs)
      const rawCode = await runAgentStep(
        client,
        modelName,
        AGENT_PROMPTS.developer.system,
        [
          { role: 'user', content: AGENT_PROMPTS.developer.user(state.pm, state.designer) }
        ],
        provider,
        'developer'
      );
      state.developerCode = extractHtml(rawCode);

      // Step 4: QA Agent (receives Developer Code + PM Specs)
      state.qa = await runAgentStep(
        client,
        modelName,
        AGENT_PROMPTS.qa.system,
        [
          { role: 'user', content: AGENT_PROMPTS.qa.user(state.pm, state.developerCode) }
        ],
        provider,
        'qa'
      );

      // Step 5: Polish Agent (receives Code + QA feedback)
      const rawPolishedCode = await runAgentStep(
        client,
        modelName,
        AGENT_PROMPTS.polish.system,
        [
          { role: 'user', content: AGENT_PROMPTS.polish.user(state.developerCode, state.qa) }
        ],
        provider,
        'polish'
      );
      state.finalCode = extractHtml(rawPolishedCode);

      sendEvent({ provider, type: 'complete', code: state.finalCode });
    } catch (err) {
      console.error(`Swarm execution aborted for ${provider}:`, err);
      sendEvent({ provider, type: 'abort', error: err.message });
    }
  };

  // Launch both swarms in parallel
  console.log('Starting Swarm Execution...');
  const cerebrasPromise = runSwarm('cerebras', cerebrasClient, 'gemma-4-31b');
  const ollamaPromise = runSwarm('ollama', ollamaClient, ollamaModel);

  // Wait for both to complete or fail
  await Promise.allSettled([cerebrasPromise, ollamaPromise]);

  console.log('Swarm Execution Finished.');
  res.write('event: close\ndata: \n\n');
  res.end();
});

app.listen(PORT, () => {
  console.log(`Backend server running on http://localhost:${PORT}`);
});
